### ISSUE TITLE
Unhealthy container?

### ISSUE THREAD

**Issue by Rubl80** [guillaumedsde/alpine-qbittorrent-openvpn#15] opened 2020-07-30 07:41 UTC
Hi @guillaumedsde 

My container is no longer working, and I have a bunch of errors in the logs. Any idea why?
It happened after an auto update from Watchtower. But I have tried to reinstall, but same error.

Error relocating /usr/lib/libtorrent-rasterbar.so.10: __fstat_time64: symbol not found

Error relocating /usr/lib/libtorrent-rasterbar.so.10: __gmtime64_r: symbol not found

Error relocating /usr/lib/libtorrent-rasterbar.so.10: __nanosleep_time64: symbol not found

Error relocating /usr/lib/libtorrent-rasterbar.so.10: __gettimeofday_time64: symbol not found

Error relocating /usr/lib/libtorrent-rasterbar.so.10: __pthread_cond_timedwait_time64: symbol not found

Error relocating /usr/lib/libtorrent-rasterbar.so.10: __stat_time64: symbol not found

Error relocating /usr/lib/libtorrent-rasterbar.so.10: __lstat_time64: symbol not found

Error relocating /usr/lib/libtorrent-rasterbar.so.10: __time64: symbol not found

Error relocating /usr/bin/qbittorrent-nox: __nanosleep_time64: symbol not found

Error relocating /usr/bin/qbittorrent-nox: _ZNK7QString8splitRefERKS_6QFlagsIN2Qt18SplitBehaviorFlagsEENS3_15CaseSensitivityE: symbol not found

Error relocating /usr/bin/qbittorrent-nox: _ZN10QJsonArrayC1EOS_: symbol not found

Error relocating /usr/bin/qbittorrent-nox: _ZN11QJsonObjectC1ESt16initializer_listI5QPairI7QString10QJsonValueEE: symbol not found

Error relocating /usr/bin/qbittorrent-nox: _ZNK7QString5splitE5QChar6QFlagsIN2Qt18SplitBehaviorFlagsEENS2_15CaseSensitivityE: symbol not found

Error relocating /usr/bin/qbittorrent-nox: _ZN7QThread4waitE14QDeadlineTimer: symbol not found

Error relocating /usr/bin/qbittorrent-nox: _ZN10QJsonArrayC1ESt16initializer_listI10QJsonValueE: symbol not found

Error relocating /usr/bin/qbittorrent-nox: __stat_time64: symbol not found

Error relocating /usr/bin/qbittorrent-nox: _ZNK7QString8splitRefE5QChar6QFlagsIN2Qt18SplitBehaviorFlagsEENS2_15CaseSensitivityE: symbol not found

Error relocating /usr/bin/qbittorrent-nox: _ZNK7QString5splitERKS_6QFlagsIN2Qt18SplitBehaviorFlagsEENS3_15CaseSensitivityE: symbol not found

**Comment by guillaumedsde** [comment] 2020-07-30 09:04
hum, strange issue, which docker tag are you using? (`python`, `latest`...)

**Comment by Rubl80** [comment] 2020-07-30 13:40
I am using 'guillaumedsde/alpine-qbittorrent-openvpn:latest'

**Comment by Rubl80** [comment] 2020-07-30 16:28
Hmm.. I just reinstalled, and now the error has changed to this:

Thu Jul 30 16:26:57 2020 cd to '/config/openvpn' failed: Permission denied (errno=13)
Thu Jul 30 16:26:57 2020 Exiting due to fatal error

I have removed the libraries completely and reinstalled, but same issue.

**Comment by Manichee** [comment] 2020-07-30 17:34
I am also getting the same error. Was working fine for almost a month until last night. This is on a Raspberry pi 4, running Raspbian Linux 10, Linux 5.4.51-v7l+ on armv7l.
`alpine-qbittorrent-openvpn_1  | Error relocating /usr/lib/libtorrent-rasterbar.so.10: __fstat_time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/lib/libtorrent-rasterbar.so.10: __gmtime64_r: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/lib/libtorrent-rasterbar.so.10: __nanosleep_time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/lib/libtorrent-rasterbar.so.10: __gettimeofday_time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/lib/libtorrent-rasterbar.so.10: __pthread_cond_timedwait_time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/lib/libtorrent-rasterbar.so.10: __stat_time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/lib/libtorrent-rasterbar.so.10: __lstat_time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/lib/libtorrent-rasterbar.so.10: __time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: __nanosleep_time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: _ZNK7QString8splitRefERKS_6QFlagsIN2Qt18SplitBehaviorFlagsEENS3_15CaseSensitivityE: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: _ZN10QJsonArrayC1EOS_: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: _ZN11QJsonObjectC1ESt16initializer_listI5QPairI7QString10QJsonValueEE: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: _ZNK7QString5splitE5QChar6QFlagsIN2Qt18SplitBehaviorFlagsEENS2_15CaseSensitivityE: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: _ZN7QThread4waitE14QDeadlineTimer: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: _ZN10QJsonArrayC1ESt16initializer_listI10QJsonValueE: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: __stat_time64: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: _ZNK7QString8splitRefE5QChar6QFlagsIN2Qt18SplitBehaviorFlagsEENS2_15CaseSensitivityE: symbol not found
alpine-qbittorrent-openvpn_1  | Error relocating /usr/bin/qbittorrent-nox: _ZNK7QString5splitERKS_6QFlagsIN2Qt18SplitBehaviorFlagsEENS3_15CaseSensitivityE: symbol not found`

**Comment by Rubl80** [comment] 2020-07-30 17:36
I´m also running same specs as @Manichee.. Maybe an ARM issue??

**Comment by guillaumedsde** [comment] 2020-07-31 08:15
> Hmm.. I just reinstalled, and now the error has changed to this:
> 
> Thu Jul 30 16:26:57 2020 cd to '/config/openvpn' failed: Permission denied (errno=13)
> Thu Jul 30 16:26:57 2020 Exiting due to fatal error
> 
> I have removed the libraries completely and reinstalled, but same issue.

the latest version of the container does not modify permissions anymore, so this issue should be fixed if you `chmod 755 /config/openvpn`

**Comment by guillaumedsde** [comment] 2020-07-31 08:16
> I am also getting the same error. Was working fine for almost a month until last night. This is on a Raspberry pi 4, running Raspbian Linux 10, Linux 5.4.51-v7l+ on armv7l.

ah, this makes more sense now, it does look like a platform compatibility issue, you guys are the first ones to test the container on arm (I only built it, but did not have an arm device on hand to try it on) I'll have a look!

**Comment by Manichee** [comment] 2020-07-31 20:56
Is there anything we can provide to help troubleshoot? Is there a way to go back to the previous working version?

**Comment by guillaumedsde** [comment] 2020-08-01 08:48
> Is there anything we can provide to help troubleshoot? Is there a way to go back to the previous working version?

I'm working on a fix right now, as soon as I have it available, I will post here.
Sadly, no there is no way to go back to the previous version because until recently, I did not make use of docker image tags very well and only overwrote the `latest` version with every update (this is fixed now, so should this come up again in the future, it will be possible to rollback)

**Comment by xyzulu** [comment] 2020-08-07 08:58
Any updates here? Still seeing this issue on arm (pi 4)

**Comment by guillaumedsde** [comment] 2020-08-07 10:35
so, I think the issue is coming from the alpine libtorrent-rasterbar package, it seems like the latest update outputs a broken binary for some reason, libtorrent 1.2.8 is released so they should update the package soon. In the meantime I've started working on a static binary of qbittorrent for multiple platforms by forking a repo with qbittorrent static build scripts, my progress is here:
 https://github.com/guillaumedsde/qbittorrent-nox-static

As soon as I have some time, I'll use that binary in the container instead of the one from the alpine repostories, this sould fix the issue

**Comment by guillaumedsde** [comment] 2020-08-09 13:20
Hey, so I've tested using the static binary on `amd64` but `arm` and `arm64` still need testing, if you pull the `guillaumedsde/alpine-qbittorrent-openvpn:fix_static_binary` image, you can test the fix, if it works, I'll merge it in master

**Comment by Manichee** [comment] 2020-08-09 13:28
> Hey, so I've tested using the static binary on `amd64` but `arm` and `arm64` still need testing, if you pull the `guillaumedsde/alpine-qbittorrent-openvpn:fix_static_binary` image, you can test the fix, if it works, I'll merge it in master

It appears to be working. Container is running now and I have access to qbittorrent.

**Comment by guillaumedsde** [comment] 2020-08-09 13:50
good to hear, I might revert back to alpine's build once they fix this issue, in any case, images are tagged on dockerhub now so it should be fairly easy to revert to an older version now

**Comment by guillaumedsde** [comment] 2020-08-09 13:51
Also, I'm merging the change into master

**Closed by guillaumedsde** 2020-08-09 13:50 UTC

**Comment by Rubl80** [comment] 2020-09-04 19:11
Hi @guillaumedsde I never got it to work on my Pi4.. I still get this error message:

cd to '/config/openvpn' failed: Permission denied (errno=13)
Exiting due to fatal error

I tried to SSH into container to "chmod 755 /config/openvpn", as you suggested. But I am not getting access to the container, so I can't chmod. I am guessing it is because the container is unhealthy.

Got any tips how to fix it?

Thanks.
