### ISSUE TITLE
`QIODevice::read (QProcess): device not open` inside WebUI

### ISSUE THREAD

**Issue by agustinmista** [guillaumedsde/alpine-qbittorrent-openvpn#118] opened 2022-02-25 13:48 UTC
Hi!

Tying to install search plugins in the qBittorrent WebUI doesn't work for me, producing the following logs:

```
... 
******** Information ********
To control qBittorrent, access the Web UI at http://localhost:8080
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
QIODevice::read (QProcess): device not open
Could not parse Nova search engine capabilities, msg:  
QIODevice::read (QProcess): device not open
Error:  
```

I didn't have much luck searching for the error message, but I found [this thread](https://github.com/qbittorrent/qBittorrent/issues/10060) in the qBittorrent repo mentioning some issues about the wrong Python version. 

Have you seen this issue before?

Thanks!

**Comment by guillaumedsde** [comment] 2022-09-20 09:23
Hi @agustinmista I've "worked around" the problem by [pinning the `python` image to python 3.8](https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/commit/0be79478d68b4deae07c0059220467f3490a846f) which seems to be [the version with which the most search plugins have been verified](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins) ideally we'd build an image for each python version, but this is something I'd like to avoid so I'll only bother adding it if the need for specific python versions is confirmed

I'm closing this issue, but don't hesitate to reopen if this does not fix the issue

**Closed by guillaumedsde** 2022-09-20 09:23 UTC
Labels: bug
